import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Nav, Footer } from "./components";
import { ClientDataContextProvider } from "./contexts/ClientDataContext";
import { ModalContextProvider } from "./contexts/ModalContex";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HouseHunt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientDataContextProvider>
          <ModalContextProvider>
            <Nav />
            {children}
          </ModalContextProvider>
        </ClientDataContextProvider>
        <Footer />
      </body>
    </html>
  );
}
